# Generated by Django 3.2.4 on 2021-07-15 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('columns', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dashboards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='High',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.IntegerField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Column', to='charts.column')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dashboards', to='charts.dashboard')),
                ('high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='High', to='charts.high')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='dashuser'),
        ),
    ]
