# Generated by Django 3.2.4 on 2021-09-09 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edit', models.IntegerField()),
                ('delete', models.IntegerField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_dashboard', to='charts.dashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
