# Generated by Django 3.2.4 on 2021-09-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210910_1609'),
        ('charts', '0002_user_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rol_Dashboard', to='users.rol'),
        ),
    ]
