# Generated by Django 3.2.4 on 2021-07-15 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210714_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_db', models.CharField(max_length=250)),
                ('name_bc', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Type_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_db', models.CharField(max_length=250)),
                ('name_bc', models.CharField(max_length=250)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Endpoint_Detail', to='endpoint.endpoint')),
                ('type_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type_detail', to='endpoint.type_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Access_rol_endpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Endpoint_Access', to='endpoint.endpoint')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rol_Access', to='users.rol')),
            ],
        ),
    ]
