# Generated by Django 3.2.4 on 2021-08-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_comparation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('signo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Type_filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=400, null=True)),
                ('type_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type_detail_1', to='endpoint.type_detail')),
                ('type_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type_filter_1', to='filter.type_filter')),
            ],
        ),
    ]
