# Generated by Django 3.2.4 on 2021-08-03 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_graph',
            name='icon',
            field=models.CharField(default='ninguno', max_length=250),
            preserve_default=False,
        ),
    ]
