# Generated by Django 3.2.4 on 2021-08-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_type_graph_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yrow',
            name='type_calculate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type_calculate', to='graphs.type_calculate'),
        ),
    ]
