# Generated by Django 3.2.4 on 2021-08-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_alter_yrow_type_calculate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_icon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='type_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type_icon', to='graphs.type_icon'),
        ),
    ]
