# Generated by Django 3.2.4 on 2021-08-21 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20210821_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_time_agrupation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='type_time_agrupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type_time_agrupation', to='graphs.type_time_agrupation'),
        ),
    ]
