# Generated by Django 3.2.4 on 2021-08-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_auto_20210821_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_agrupation',
            name='card',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
