# Generated by Django 3.2.4 on 2021-08-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
        ('endpoint', '0001_initial'),
        ('graphs', '0006_type_agrupation_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Graph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comparate_value', models.CharField(max_length=400)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Filter', to='filter.filter')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Graph_Filter', to='graphs.graph')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Value', to='endpoint.detail')),
            ],
        ),
    ]
