# Generated by Django 3.2.4 on 2021-08-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
        ('filter', '0001_initial'),
        ('graphs', '0007_filter_graph'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filter_Graph',
            new_name='Graph_Filter',
        ),
    ]
