# Generated by Django 3.2.4 on 2021-08-26 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
        ('graphs', '0008_rename_filter_graph_graph_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_filter',
            name='type_comparation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type_comparation', to='filter.type_comparation'),
        ),
    ]
