# Generated by Django 3.2.4 on 2021-08-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0009_graph_filter_type_comparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph_filter',
            name='comparate_value',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
