# Generated by Django 3.2.4 on 2021-07-16 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210714_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expirate',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 14, 11, 23, 310898)),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.rol'),
        ),
    ]
