# Generated by Django 3.2.4 on 2021-07-26 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210716_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expirate',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 23, 5, 38, 761326)),
        ),
    ]
