# Generated by Django 3.2.4 on 2021-08-30 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_expirate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expirate',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 0, 8, 26, 817554)),
        ),
    ]
