# Generated by Django 3.2.4 on 2021-09-10 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_expirate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='create',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='expirate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 16, 9, 10, 433671)),
        ),
    ]
