# Generated by Django 3.2.4 on 2021-10-05 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210910_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expirate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 12, 7, 37, 85421)),
        ),
    ]
