# Generated by Django 3.2.4 on 2021-10-07 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_expirate'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='name',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='Name of User'),
        # ),
        migrations.AlterField(
            model_name='user',
            name='expirate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 0, 52, 49, 799241)),
        ),
    ]
