# Generated by Django 3.2.4 on 2021-11-03 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211007_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expirate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 1, 50, 33, 285684)),
        ),
    ]
