# Generated by Django 3.2.4 on 2021-11-03 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_expirate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expirate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 1, 59, 36, 254246)),
        ),
    ]
