# Generated by Django 2.2.6 on 2021-01-11 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_since', models.DateTimeField(null=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_lastname', models.CharField(max_length=100)),
                ('consultor', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=200, null=True)),
                ('refresh_token', models.CharField(max_length=200, null=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('nonauto', models.BooleanField(null=True)),
                ('customer_id', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('color', models.CharField(max_length=20, null=True)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('application_key', models.CharField(max_length=200)),
                ('application_secret', models.CharField(max_length=200)),
                ('developer_token', models.CharField(max_length=200)),
                ('auth_uri', models.CharField(max_length=200)),
                ('callback_uri', models.CharField(max_length=200)),
                ('access_uri', models.CharField(max_length=200)),
                ('permissions_uri', models.CharField(max_length=200)),
                ('user_info_uri', models.CharField(max_length=200, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Network')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blueprint', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Client')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Network')),
            ],
        ),
        migrations.CreateModel(
            name='StoreConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Connector')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Store')),
            ],
        ),
        migrations.CreateModel(
            name='SocialApplicationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=100)),
                ('separator', models.CharField(max_length=10, null=True)),
                ('social_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.SocialApplication')),
            ],
        ),
        migrations.CreateModel(
            name='LinioStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktp', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Store')),
            ],
        ),
        migrations.AddField(
            model_name='connector',
            name='social_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.SocialApplication'),
        ),
        migrations.AddField(
            model_name='connector',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
