# Generated by Django 2.2.6 on 2021-01-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='network',
        ),
    ]
