# Generated by Django 2.2.6 on 2021-01-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_store_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialapplication',
            name='application_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
