# Generated by Django 2.2.6 on 2021-01-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_socialapplication_application_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('marketplace_id', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Connector')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Marketplace')),
            ],
        ),
    ]
