# Generated by Django 2.2.6 on 2021-02-12 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_marketplace_marketplaceconnector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='refresh_token',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='MonthGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('fee', models.FloatField()),
                ('sales_goal', models.FloatField()),
                ('units_goal', models.FloatField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Store')),
            ],
        ),
    ]
