# Generated by Django 2.2.6 on 2021-02-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20210211_1833'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='monthgoals',
            constraint=models.UniqueConstraint(fields=('store', 'mes', 'anio'), name='UC_StoreMesAnio_MonthGoals'),
        ),
    ]
