# Generated by Django 2.2.6 on 2021-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210211_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthgoals',
            name='ads_spend_limit',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
