# Generated by Django 2.2.6 on 2021-03-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_monthgoals_ads_spend_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='access_token',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='customer_id',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='connector',
            name='refresh_token',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
