# Generated by Django 2.2.20 on 2021-04-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_homologation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
