# Generated by Django 2.2.20 on 2021-04-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20210416_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ktp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
