# Generated by Django 2.2.20 on 2021-04-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20210416_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.PositiveSmallIntegerField()),
                ('ktp', models.CharField(max_length=100, null=True)),
                ('sku', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=300, null=True)),
                ('categoria', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
