# Generated by Django 2.2.20 on 2021-08-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_itemaction_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='item_temp',
            name='nombre',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
