# Generated by Django 2.2.20 on 2021-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20210817_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_temp',
            name='costo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
