# Generated by Django 2.2.20 on 2021-09-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_item_temp_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_temp',
            name='costo',
        ),
        migrations.AddField(
            model_name='item',
            name='costo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
