# Generated by Django 2.2.20 on 2021-09-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_auto_20210901_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='marketplace',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
