# Generated by Django 2.2.20 on 2021-09-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_item_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_temp',
            name='marketplace',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
