# Generated by Django 2.2.20 on 2021-09-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20210903_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemaction',
            name='ktp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('Activado', 'Activado'), ('Desactivado', 'Desactivado')], max_length=100),
        ),
    ]
