# Generated by Django 2.2.20 on 2021-09-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_itemaction_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categoria',
            new_name='plataforma',
        ),
        migrations.RenameField(
            model_name='item_temp',
            old_name='categoria',
            new_name='plataforma',
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Activado', 'Activado'), ('Desactivado', 'Desactivado')], max_length=100),
        ),
    ]
