# Generated by Django 3.2.4 on 2021-10-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_auto_20211006_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='logo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
