# Generated by Django 3.2.4 on 2021-11-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_marketplace_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='owner_name',
            field=models.CharField(max_length=100, verbose_name='Store Name'),
        ),
    ]
